### ISSUE TITLE
HTTP Error 403 when setting owners of an Application

### ISSUE THREAD

**Issue by TechWatching** [pulumi/pulumi-azuread#68]
I have the following error when trying to set the `Owners` property of an `ApplicationArgs`:
```
Error while adding owners to Azure AD applications with ID "****-****-****-***-****": 
Error adding owner "****-****-****-****-****" to Azure AD applications with ID "****-****-****-***-****":
graphrbac.ApplicationsClient#AddOwner: Failure responding to request: StatusCode=403 -- 
Original Error: autorest/azure: Service returned an error. 
Status=403 Code="Unknown" Message="Unknown service error" 
Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-05-13T10:54:33","message":{"lang":"en","value":"Insufficient privileges to complete the operation."}}]
```
By default, when not specified, the owner is set to the SP deploying the resources and it works fine. However if I try to set the Owners property with an InputList containing a user and my SP name, it fails.

It could be linked to [this issue](https://github.com/terraform-providers/terraform-provider-azuread/issues/203) on terraform provider.

**Comment by leezen** [comment]
What version of the provider are you using? We've merged that upstream change a while back.

**Comment by TechWatching** [comment]
I did not event think about my nuget package version. I was in version 2.0.1 of azuread provider. I have just  upgraded to 2.1.1, I still have the same error.

**Comment by RehanSaeed** [comment]
I've been getting a 403 when calling `new Application(appName, new ApplicationArgs() { DisplayName = appName })` have have raised https://github.com/pulumi/pulumi-azuread/issues/246. Is this issue related?

**Comment by mikhailshilkov** [comment]
The upstream issue has been closed, the linked issue has been closed, and this issue is more than 3 years ago, and it doesn't have a repro program. I'll go ahead and close it as fixed/stale. Please open a new issue if the problem still exists today.
